# Generated by Django 6.1.2 on 2026-10-06 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_transplant_center', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_code', models.CharField(max_length=50, unique=True)),
                ('donor_name', models.CharField(max_length=150)),
                ('donor_type', models.CharField(choices=[('DECEASED', 'Deceased Donor (Cadaveric)'), ('LIVING', 'Living Donor')], default='DECEASED', max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=5)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('cause_of_death', models.CharField(blank=True, max_length=255)),
                ('time_of_death', models.DateTimeField(blank=True, null=True)),
                ('family_consent_verified', models.BooleanField(default=True)),
                ('legal_clearance', models.BooleanField(default=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='organ_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_id', models.CharField(max_length=50, unique=True)),
                ('organ_type', models.CharField(choices=[('KIDNEY', 'Kidney'), ('LIVER', 'Liver'), ('HEART', 'Heart'), ('LUNG', 'Lung'), ('PANCREAS', 'Pancreas'), ('CORNEA', 'Cornea')], max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=5)),
                ('harvested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viability_hours', models.PositiveIntegerField(default=24, help_text='Cold ischemia time window in hours')),
                ('condition_grade', models.CharField(choices=[('EXCELLENT', 'Grade A - Excellent'), ('GOOD', 'Grade B - Good'), ('FAIR', 'Grade C - Fair')], default='EXCELLENT', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Matching'), ('ALLOCATED', 'Allocated to Patient'), ('IN_TRANSIT', 'In Transit / Cold Storage'), ('TRANSPLANTED', 'Transplanted'), ('EXPIRED', 'Viability Expired')], default='AVAILABLE', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='organ_app.donorrecord')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs_in_stock', to='organ_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='MortuaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('deceased_name', models.CharField(max_length=150)),
                ('deceased_id_number', models.CharField(blank=True, help_text='Hospital Registration / Govt ID', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=5)),
                ('time_of_death', models.DateTimeField()),
                ('cause_of_death', models.TextField()),
                ('mortuary_room_location', models.CharField(help_text='E.g., Storage Bay 3, Cold Vault 4', max_length=100)),
                ('is_potential_donor', models.BooleanField(default=False)),
                ('donor_flag_reason', models.TextField(blank=True, help_text='E.g., Brain death criteria fulfilled, organs preserved')),
                ('donor_status_verified', models.BooleanField(default=False, help_text='Family consent / NOTTO donor card check')),
                ('organs_harvestable', models.CharField(blank=True, help_text='Comma-separated organs, e.g. Kidney, Liver, Cornea', max_length=255)),
                ('alert_sent_to_hospital', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortuary_records', to='organ_app.hospital')),
                ('linked_donor_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_sources', to='organ_app.donorrecord')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortuary_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=50, unique=True)),
                ('organ', models.CharField(choices=[('KIDNEY', 'Kidney'), ('LIVER', 'Liver'), ('HEART', 'Heart'), ('LUNG', 'Lung'), ('PANCREAS', 'Pancreas'), ('CORNEA', 'Cornea')], max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=5)),
                ('medical_history', models.TextField(help_text='Detailed diagnosis, clinical justification, previous surgeries')),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted - Pending Medical Review'), ('DOCTOR_VERIFIED', 'Doctor Verified - Pending Govt Approval'), ('DOCTOR_REJECTED', 'Doctor Rejected'), ('GOVT_APPROVED', 'Government Approved - Waiting for Organ'), ('GOVT_REJECTED', 'Government Authorization Denied'), ('ALLOCATED', 'Organ Matched & Allocated'), ('TRANSPLANTED', 'Transplant Procedure Completed'), ('CANCELLED', 'Request Cancelled')], default='SUBMITTED', max_length=30)),
                ('priority_level', models.CharField(choices=[('EMERGENCY', 'Tier 1 - Emergency (Critical Condition)'), ('HIGH', 'Tier 2 - High Priority'), ('NORMAL', 'Tier 3 - Normal Priority')], default='NORMAL', max_length=20)),
                ('doctor_verified_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('govt_approved_at', models.DateTimeField(blank=True, null=True)),
                ('govt_notes', models.TextField(blank=True)),
                ('govt_approval_number', models.CharField(blank=True, help_text='Official Government Legal Certification ID', max_length=100)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_requests', to='organ_app.availableorgan')),
                ('doctor_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_verifications', to=settings.AUTH_USER_MODEL)),
                ('govt_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='govt_approvals', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to='organ_app.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success / Approval'), ('WARNING', 'Alert / Action Needed'), ('EMERGENCY', 'Critical Urgent Notification')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_app.organrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=80)),
                ('from_state', models.CharField(blank=True, max_length=60)),
                ('to_state', models.CharField(blank=True, max_length=60)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_app.availableorgan')),
                ('mortuary_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ_app.mortuaryrecord')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organ_app.organrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor / Medical Officer'), ('GOVT', 'Government Official'), ('HOSPITAL', 'Hospital Transplant Coordinator'), ('MORTUARY', 'Mortuary Staff'), ('ADMIN', 'System Administrator')], default='PATIENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, help_text='National Identification / Aadhar', max_length=50)),
                ('license_or_emp_id', models.CharField(blank=True, help_text='Medical license / Govt ID / Employee number', max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+ (A Positive)'), ('A-', 'A- (A Negative)'), ('B+', 'B+ (B Positive)'), ('B-', 'B- (B Negative)'), ('AB+', 'AB+ (AB Positive)'), ('AB-', 'AB- (AB Negative)'), ('O+', 'O+ (O Positive)'), ('O-', 'O- (O Negative)')], max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='organ_app.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
